---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by thexkey.
--- Description: DarkRP/BuildRP support for Statistics.
--- DateTime: 9/20/2021 5:25 PM
---

--- TODO: figure out how to check money via a Hook for other things than pickup/drop money

local db = STATS.Database
STATS.Queries['darkrp_get'] = db:prepare('SELECT * FROM stats_darkrp WHERE steamid64 = ?')
STATS.Queries['darkrp_update'] = db:prepare('UPDATE stats_darkrp SET money = ?, kills = ?, deaths = ? WHERE steamid64 = ?')
STATS.Queries['darkrp_new'] = db:prepare('INSERT INTO stats_darkrp VALUES (?, 0, 0, 0)')

function STATS:FetchDarkRPStats(ply)
    if ply:IsBot() then return end
    local id = ply:SteamID64()
    if not id then return end

    ply.DarkRPStats = {}

    local q = STATS.Queries['darkrp_get']
    q:setString(1, id)
    function q:onSuccess(data)
        if type(data) == 'table' and #data > 0 then
            ply.DarkRPStats = data[1]
        else
            local q2 = STATS.Queries['darkrp_new']
            q2:setString(1, id)
            q2:start()

            ply.DarkRPStats = {
                ['money'] = ply:getDarkRPVar("money") or 0,
                ['kills'] = 0,
                ['deaths'] = 0
            }
        end
    end
    q:start()
end

function STATS:SaveDarkRPStats(ply)
    if not ply.DarkRPStats then return end
    local id = ply:SteamID64()

    local q = STATS.Queries['darkrp_update']
    q:setNumber(1, ply.DarkRPStats['money'])
    q:setNumber(2, ply.DarkRPStats['kills'])
    q:setNumber(3, ply.DarkRPStats['deaths'])
    q:setString(4, id)
    q:start()
end

hook.Add('PlayerInitialSpawn', 'UpdateDarkRPStatistics', function(ply) STATS:FetchDarkRPStats(ply) end)

--- TODO: fix this god damn function being nil (stats_main.lua complains when it is when saving data!)
hook.Add('UpdateStatistics', 'UpdateDarkRPStatistics', function(ply) STATS:SaveDarkRPStats(ply) end)

--- Track Death events.
hook.Add('PlayerDeath', 'DarkRPKillStatistics', function(victim, inflictor, attacker)

    -- sanity checks
    if victim == attacker then return end
    if not attacker:IsPlayer() then return end
    if not attacker.DarkRPStats then return end

    -- do the thing
    victim.DarkRPStats['deaths'] = victim.DarkRPStats['deaths'] + 1
    attacker.DarkRPStats['kills'] = attacker.DarkRPStats['kills'] + 1

    -- track their money just incase we lose/gain any money during the events.
    victim.DarkRPStats['money'] = victim:getDarkRPVar("money")
    attacker.DarkRPStats['money'] = attacker:getDarkRPVar("money")

end)

--- Track player cash drop/pickup.

---  Cash related Actions
hook.Add('playerPickedUpMoney','DarkRPMoneyStatistics', function(ply, amount, ent)
    if ply:IsPlayer() then return end
    if not ply.DarkRPStats then return end

    ply.DarkRPStats['money'] = ply.DarkRPStats['money'] + amount

end)
hook.Add('playerDroppedMoney','DarkRPMoneyStatistics', function(ply, amount, ent)
    if ply:IsPlayer() then return end
    if not ply.DarkRPStats then return end

    ply.DarkRPStats['money'] = ply.DarkRPStats['money'] - amount

end)
--- Cheque related Actions
hook.Add('playerPickedUpCheque','DarkRPMoneyStatistics', function(ply, ply2, amount, success, ent)
    if ply:IsPlayer() then return end
    if not ply.DarkRPStats then return end
    if success == false then return end

    ply.DarkRPStats['money'] = ply.DarkRPStats['money'] + amount

end)
hook.Add('playerToreUpCheque','DarkRPMoneyStatistics', function(ply, ply2, amount, ent)
    if ply:IsPlayer() then return end
    if not ply.DarkRPStats then return end

    ply.DarkRPStats['money'] = ply.DarkRPStats['money'] + amount

end)
hook.Add('playerDroppedCheque','DarkRPMoneyStatistics', function(ply, ply2, amount, ent)
    if ply:IsPlayer() then return end
    if not ply.DarkRPStats then return end

    ply.DarkRPStats['money'] = ply.DarkRPStats['money'] - amount

end)
